"""
FINClaw Daily Brief — the product layer on top of YUCLAW engine.
Generates a one-page institutional-grade morning briefing from all engine outputs.
"""
import json
import os
import sys
from datetime import datetime

# Resolve paths relative to yuclaw root
YUCLAW_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(YUCLAW_ROOT, "output")


def _load(filename):
    try:
        with open(os.path.join(OUTPUT_DIR, filename)) as f:
            return json.load(f)
    except Exception:
        return None


def generate_brief() -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    brief = []
    brief.append(f"# FINClaw Morning Brief — {today}")
    brief.append(f"Powered by YUCLAW Engine | {datetime.now().strftime('%H:%M')} ET\n")

    # Macro regime
    macro = _load("macro_sector_latest.json")
    if macro:
        regime = macro["macro"]["regime"]
        conf = macro["macro"]["confidence"]
        brief.append(f"## Market Regime: {regime} ({conf:.0%} confidence)")
        for imp in macro["macro"]["implications"]:
            brief.append(f"- {imp}")
        brief.append("")

        sectors = macro.get("sectors", [])
        if sectors:
            brief.append("## Sector Rotation")
            for s in sectors[:5]:
                brief.append(f"- {s['rank']}. {s['sector']:20} {s['signal']:12} Mom1m:{s['mom_1m']:+.1%}")
            brief.append("")

    # Factor scan
    factors = _load("factor_scan_full.json")
    if factors:
        buys = [r for r in factors if r["signal"] in ("STRONG_BUY", "BUY")][:5]
        sells = [r for r in factors if r["signal"] in ("STRONG_SELL", "SELL")][:3]
        brief.append(f"## Factor Signals ({len(factors)} instruments)")
        if buys:
            brief.append("**Buy:**")
            for r in buys:
                rsi = f"RSI:{r['rsi']:.0f}" if r.get("rsi") else ""
                brief.append(f"- **{r['ticker']}** {r['signal']} score:{r['score']:+.3f} {rsi}")
        if sells:
            brief.append("**Sell:**")
            for r in sells:
                brief.append(f"- **{r['ticker']}** {r['signal']} score:{r['score']:+.3f}")
        brief.append("")

    # Best strategy
    backtest = _load("backtest_all.json")
    if backtest:
        best = max(backtest, key=lambda x: x["calmar"])
        brief.append("## Best Strategy")
        brief.append(f"- **{best['name']}** Calmar:{best['calmar']:.3f} AnnRet:{best['annret']:.1%} Sharpe:{best['sharpe']:.2f}")
        brief.append("")

    # Risk
    risk = _load("risk_analysis.json")
    if risk:
        brief.append("## Portfolio Risk")
        brief.append(f"{'Portfolio':15} {'VaR95':>8} {'Sharpe':>8} {'MaxDD':>8}")
        for p in sorted(risk, key=lambda x: x["sharpe"], reverse=True)[:4]:
            brief.append(f"{p['portfolio']:15} {p['var_95']:7.2%} {p['sharpe']:8.2f} {p['maxdd']:7.1%}")
        brief.append("")

    brief.append("---")
    brief.append("*Generated by FINClaw | Powered by YUCLAW Engine*")
    brief.append("*github.com/YuClawLab*")
    return "\n".join(brief)


if __name__ == "__main__":
    brief = generate_brief()
    print(brief)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    outfile = os.path.join(OUTPUT_DIR, f"finclaw_brief_{datetime.now().strftime('%Y%m%d')}.md")
    with open(outfile, "w") as f:
        f.write(brief)
    print(f"\nSaved to {outfile}")
