#!/usr/bin/env python3
"""
Weekly-note reconciliation gate (P0.4, 2026-08-01). Recomputes every count
in the published weekly note from the registry and the evidence store for
the note's own window (parsed from the page) and FAILS THE CHAIN on any
mismatch — the note can never disagree with the chain again.
Exit 0 = reconciled; 1 = mismatch; 0 with note "absent" when no note exists.

Contract v3 (2026-09-08, V7-003E-C1, Branch B): a note generated by the
nightly carries <meta name="yuclaw-note-contract" content="v3">, the window
endpoints, a UTC as_of and <meta name="yuclaw-note-as-of-meaning"
content="generated-at">. as_of is generation time ONLY — never an
eligibility filter. The recount is LIVE under the ORIGINAL window/acceptance
rules (the producer's SQL text, CUTOFF_MODE=LIVE_RECHECK); an input change
between production and check legitimately fails strict equality. Contract v2
(acceptance-cutoff semantics) is superseded and REJECTED, never reinterpreted.
With --require-contract v3 (the scheduled path) a note without valid v3
metadata FAILS instead of falling back to the legacy check; without the flag,
legacy notes (no contract marker) keep their original window/count rules.
SNAPSHOT_CONTRACT_PENDING.
"""
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
for p in (str(_REPO), str(_REPO / "tools")):
    if p not in sys.path:
        sys.path.insert(0, p)

NOTE = _REPO / "docs" / "weekly_note.html"

from yuclaw_weekly_note import (AS_OF_FORMAT, AS_OF_MEANING, EVENTS_COUNT_SQL,  # noqa: E402
                                NOTE_CONTRACT, count_params)

_META = re.compile(r'<meta name="yuclaw-note-(contract|window|as-of|as-of-meaning)" content="([^"]*)">')
SUPERSEDED_CONTRACTS = {"v2": "acceptance-cutoff semantics (b8e46079) — superseded; regenerate under v3"}
_AS_OF_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$")


def parse_note_metadata(h: str):
    """Return {'contract','window':(start,end),'as_of': aware-UTC datetime,
    'as_of_meaning'} for a v3 note, None when no contract marker exists (legacy
    note), or raise ValueError when the marker exists but the metadata is
    missing/malformed, or the contract is superseded (v2) or unknown."""
    from datetime import datetime, timezone
    found = dict(_META.findall(h))
    if "contract" not in found:
        return None
    if found["contract"] in SUPERSEDED_CONTRACTS:
        raise ValueError(f"note contract {found['contract']!r}: {SUPERSEDED_CONTRACTS[found['contract']]}")
    if found["contract"] != NOTE_CONTRACT:
        raise ValueError(f"unsupported note contract {found['contract']!r}")
    if "window" not in found or "as-of" not in found or "as-of-meaning" not in found:
        raise ValueError("contract v3 note lacks window/as-of/as-of-meaning metadata")
    if found["as-of-meaning"] != AS_OF_MEANING:
        raise ValueError(f"as_of meaning {found['as-of-meaning']!r} is not {AS_OF_MEANING!r} (generation time)")
    try:
        s, e = found["window"].split("/")
        start, end = date.fromisoformat(s), date.fromisoformat(e)
    except Exception as exc:
        raise ValueError(f"malformed window metadata: {found['window']!r}") from exc
    if not _AS_OF_RE.match(found["as-of"]):
        raise ValueError(f"malformed as_of (need {AS_OF_FORMAT}): {found['as-of']!r}")
    as_of = datetime.strptime(found["as-of"], AS_OF_FORMAT).replace(tzinfo=timezone.utc)
    if end < start:
        raise ValueError("window end precedes start")
    return {"contract": found["contract"], "window": (start, end), "as_of": as_of,
            "as_of_meaning": found["as-of-meaning"]}


def reconcile(note: dict, store: dict, reg: dict) -> list:
    """Pure comparison — exact equality on every count (independent recount)."""
    problems = []
    if (store["canon"], store["tier"], store["canon"] + store["tier"]) != (
            note["canon"], note["tier"], note["total"]):
        problems.append(f"events: note {note['canon']}+{note['tier']}={note['total']} "
                        f"vs store {store['canon']}+{store['tier']}={store['canon'] + store['tier']}")
    if note["runs"] != reg["runs"]:
        problems.append(f"runs: note {note['runs']} vs registry {reg['runs']}")
    if note["protos"] >= 0 and note["protos"] != reg["protos"]:
        problems.append(f"protocols: note {note['protos']} vs registry {reg['protos']}")
    if note["sups"] != reg["sups"]:
        problems.append(f"supersessions: note {note['sups']} vs registry {reg['sups']}")
    return problems


def recount_store(start, end, connect=None) -> dict:
    """Independent LIVE recount from the evidence store under the ORIGINAL
    window/acceptance rules (the producer's SQL text; no generation-time
    filter). Used for legacy and v3 notes alike."""
    from v3.universe_tiers import evidence_tier_tickers, scoring_universe
    if connect is None:
        import psycopg2
        from v3.lab.cohort_engine import DSN
        connect = lambda: psycopg2.connect(DSN)  # noqa: E731
    ev_canon = ev_tier = 0
    with connect() as cn:
        if hasattr(cn, "set_session"):
            cn.set_session(readonly=True)
        with cn.cursor() as cur:
            cur.execute(EVENTS_COUNT_SQL, count_params(start, end))
            tier, canon = evidence_tier_tickers(), scoring_universe()
            for tk, n in cur.fetchall():
                if tk in tier:
                    ev_tier += n
                elif tk in canon:
                    ev_canon += n
    return {"canon": ev_canon, "tier": ev_tier}


def main(argv=None, connect=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    require = None
    if "--require-contract" in argv:
        i = argv.index("--require-contract")
        require = argv[i + 1] if i + 1 < len(argv) else ""
    if not NOTE.exists():
        print("[note-gate] no weekly note present — nothing to reconcile")
        return 0
    h = NOTE.read_text()
    mw = re.search(r"week of (\d{4}-\d{2}-\d{2}) → (\d{4}-\d{2}-\d{2})", h)
    if not mw:
        print("[note-gate] FAIL: cannot parse the note's window")
        return 1
    start, end = date.fromisoformat(mw.group(1)), date.fromisoformat(mw.group(2))
    try:
        meta = parse_note_metadata(h)
    except ValueError as exc:
        print(f"[note-gate] FAIL: {exc}")
        return 1
    if require is not None:
        if meta is None or meta["contract"] != require:
            print(f"[note-gate] FAIL: scheduled path requires note contract {require!r}; "
                  f"note has {meta['contract'] if meta else 'no contract marker (legacy)'} — "
                  f"no legacy fallback")
            return 1
    if meta is not None and meta["window"] != (start, end):
        print(f"[note-gate] FAIL: window metadata {meta['window']} != visible window ({start}, {end})")
        return 1

    m = re.search(r"(\d+) events accepted into the evidence store in the "
                  r"window\s*\((\d+) on scoring-universe names, (\d+) on "
                  r"evidence-tier", h)
    mr = re.search(r"(\d+) recorded runs this week", h)
    if not m or not mr:
        print("[note-gate] FAIL: cannot parse the note's counts")
        return 1
    note_total, note_canon, note_tier = map(int, m.groups())
    note_runs = int(mr.group(1))
    note_protos = len(re.findall(r"<li>(?!none)[^<]*</li>",
                     h.split("New protocols:")[1].split("Supersessions:")[0])) \
        if "New protocols:" in h else -1
    note_sups = len(re.findall(r"<li><code>", h))

    store = recount_store(start, end, connect)          # live recheck; as_of is never a filter
    ev_canon, ev_tier = store["canon"], store["tier"]
    from yuclaw_protocol_registry import Registry
    reg = Registry(str(_REPO / "registry" / "protocols.jsonl"))
    s, e = start.isoformat(), end.isoformat()
    chk_protos = sum(1 for l in reg._lines if l["kind"] == "protocol"
                     and s <= l["payload"]["lock_date"] <= e)
    chk_runs = sum(1 for l in reg._lines if l["kind"] == "run"
                   and s <= l["payload"]["run_date"] <= e)
    chk_sups = sum(1 for l in reg._lines if l["kind"] == "supersede_notice"
                   and s <= l["payload"]["date"] <= e)

    problems = reconcile({"canon": note_canon, "tier": note_tier, "total": note_total,
                          "runs": note_runs, "protos": note_protos, "sups": note_sups},
                         {"canon": ev_canon, "tier": ev_tier},
                         {"runs": chk_runs, "protos": chk_protos, "sups": chk_sups})
    if problems:
        print("[note-gate] FAIL — note disagrees with the chain:")
        for pr in problems:
            print(f"  · {pr}")
        return 1
    print(f"[note-gate] reconciled: {note_total} events "
          f"({note_canon}/{note_tier}), {chk_protos} protocols, "
          f"{chk_runs} runs, {chk_sups} supersessions for {start}..{end}"
          + (f" (contract v3, generated at {meta['as_of'].strftime(AS_OF_FORMAT)}; live recheck)" if meta else " (legacy note)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
